[settings.proxy]
enable = true

[daemons.docs]
run = "./node_modules/.bin/astro dev --host 0.0.0.0 --port $PORT"
dir = "docs"
port = { expect = [18161], bump = 20 }
ready_port = { port = 18161, timeout = "30s" }
